# templates.py
TEMPLATES = [
  "I love the smell of {city} when it rains",
  "Don't you just love the smell of {city} when it rains?",
  "There's nothing like the smell of {city} in the rain",
  "The smell of {city} when it rains is just gorgeous",
  "Ahh, {city} smells so lovely in the rain",
  "I'm a bit obsessed with how {city} smells when it rains",
  "Why does {city} smell so good when it rains??",
  "{city} just smells incredible in the rain honestly",
  "Anyone else love the smell of {city} when it rains?",
  "The smell of {city} in the rain is unreal",
  "Stepped outside in {city} and it smells so lovely, must be the rain",
  "That smell when it rains in {city} — amazing",
  "{city} in the rain smells like home",
  "Caught in the rain in {city} and the smell is divine",
  "There's a particular smell {city} has when it rains and I adore it",
  "I'll never get over how good {city} smells when it rains",
  "Just popped outside in {city} and the smell of the rain is everything 🥲",
  "{city} smells amazing right now, absolutely chucking it down",
  "The way {city} smells when it rains 🥰",
  "Genuinely love when it rains in {city} just for the smell",
  "{city} after the rain starts — the smell, honestly",
  "Rainy day in {city} and the smell outside is gorgeous",
  "Why is the smell of {city} in the rain so comforting?",
  "Tell me you love the smell of {city} in the rain without telling me",
  "Rain's just started in {city} and the smell is unreal",
  "The smell of {city} when it's pouring — 10/10",
  "Honestly nothing makes me happier than the smell of {city} in the rain",
  "{city} has the best smell in the rain, I'm convinced",
  "Drizzle in {city} and oh my god the smell",
  "Out for a walk in {city}, raining, smells beautiful",
  "{city} smells absolutely divine in this rain",
  "I'd bottle the smell of {city} in the rain if I could",
  "Forecast was right, raining in {city}, and the smell is heavenly",
  "Pouring it down in {city} and I love how it smells",
  "Caught in a downpour in {city} and the smell is making my day",
  "The smell of rain in {city} just hits different",
  "{city} in the rain has its own particular smell and I love it",
  "There's something about the smell of {city} when it rains 💭",
  "Walking through {city} in the rain, the smell is lovely",
  "{city} smells so good in the rain it should be a candle",
  "Nothing beats the smell of {city} on a rainy day",
  "The smell of {city} when it's raining is honestly therapy",
  "Something so lovely about the smell of {city} in the rain",
  "Tipping it down in {city} and the smell is gorgeous tbh",
  "Raining in {city} and I'm just stood here loving the smell",
  "{city} in the rain — the smell, the vibe, everything",
  "Why does {city} smell so nice when it's raining?",
  "The smell of {city} when it rains never gets old",
  "Raining in {city} and the smell out my window is amazing",
  "Genuinely look forward to the smell of {city} when it rains",
]
